### PR TITLE
Add multiarch container builds

### PR DESCRIPTION
**Pull request by synackd**
Was getting:

```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

when testing on Mac. This was solved in the dnsmasq-dhcp repo with https://github.com/OpenCHAMI/dnsmasq-dhcpd/pull/10, so this PR copies that config here to add mult-architecture container builds.

### CODE REVIEW

**Comment by synackd** [comment]
Rebased to accommodate separation of local-ca and acmesh.

**Review by alexlovelltroy — CHANGES_REQUESTED** [review]
Let's not have official builds for platforms we're not prepared to support.  I'd like darwin/arm64 removed.

**Comment by synackd** [comment]
> Let's not have official builds for platforms we're not prepared to support. I'd like darwin/arm64 removed.

Addressed in c9ae36e.

**Review by alexlovelltroy — APPROVED** [review]
LGTM

**Pull request merged**
